"""add user_name column to UserModel

Revision ID: 8084b9f8e365
Revises: f849806872cd
Create Date: 2026-05-18 19:08:43.224868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8084b9f8e365"
down_revision: Union[str, Sequence[str], None] = "f849806872cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_tokens_expires_at"), "tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_tokens_revoked"), "tokens", ["revoked"], unique=False)
    op.add_column("users", sa.Column("user_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_name")
    op.drop_index(op.f("ix_tokens_revoked"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_expires_at"), table_name="tokens")
    # ### end Alembic commands ###
