"""add revoked_at to RefreshTokenModel

Revision ID: f849806872cd
Revises: 0217a5a470db
Create Date: 2026-05-15 23:48:52.738356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f849806872cd"
down_revision: Union[str, Sequence[str], None] = "0217a5a470db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("revoked", sa.Boolean(), nullable=False))
    op.add_column(
        "tokens", sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("tokens", "revoke")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("revoke", sa.BOOLEAN(), nullable=False))
    op.drop_column("tokens", "revoked_at")
    op.drop_column("tokens", "revoked")
    # ### end Alembic commands ###
